### ISSUE TITLE
Not emptying the output when moving the window on different monitor (?workspace)

### ISSUE THREAD

**Issue by webwalkerkarma** [FieldofClay/hyprland-activewindow#4] opened 2024-01-10 17:03 UTC
**Version in use:**
- [AUR](https://aur.archlinux.org/packages/hyprland-activewindow): hyprland-activewindow 0.4.4-1

**STR:**
1. Setup eww bar using active window per each monitor on 2+ monitors ([my setup](https://pastebin.com/vu1UNqSj))
2. Spawn any window with title -> title name is correct
3. Move the window on different screen -> title name is still displayed for the window that is no longer existing in the workspace

**Expected:** Title name should be empty when the window is moved to another monitor/workspace 

[Video 1](https://imgur.com/JljScK0) (empty workspace)
[Video 2](https://imgur.com/ba02oZb) (workspace with other windows)

**Comment by FieldofClay** [comment] 2024-01-11 00:16
Ah, I see what the problem is here, thanks for pointing it out. 

I really need to refactor the code, so will fix this when I do that. Should have time in the next week or two.

**Comment by FieldofClay** [comment] 2024-01-26 02:01
Please try v0.5.0, should be fixed now.

**Closed** 2024-02-17 05:49 UTC
